# Generated by Django 3.2.11 on 2022-01-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleCate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateidx', models.IntegerField(unique=True)),
                ('catename', models.CharField(max_length=30)),
            ],
        ),
    ]
