# Generated by Django 3.2.11 on 2022-01-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_middlecate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_level',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
